<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/01/30 16:01:21
sfConfig::add(array(
  'app_web_path' => 'http://ram.jbl.svs153',
  'app_upload_webpath' => '/home/ramesh/web/www.jbl.com/web/uploads',
));
