<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/30 16:01:21

$database = new sfPropelDatabase();
$database->initialize(array (
  'persistent' => true,
  'dsn' => 'mysql://svs:svs@localhost/ram_jbl',
), 'propel');
$this->databases['propel'] = $database;
