<?php
// auto-generated by sfRoutingConfigHandler
// date: 2015/01/30 16:01:21
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'home' => 
  array (
    0 => '/home',
    1 => '#^/home$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'about-us' => 
  array (
    0 => '/about-us',
    1 => '#^/about-us$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'aboutUs',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'contact-us' => 
  array (
    0 => '/contact-us',
    1 => '#^/contact-us$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'contactUs',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'new-market' => 
  array (
    0 => '/new-market',
    1 => '#^/new-market$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'newMarket',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'products' => 
  array (
    0 => '/products',
    1 => '#^/products$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'products',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_symfony' => 
  array (
    0 => '/symfony/:action/*',
    1 => '#^/symfony(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'action',
    ),
    3 => 
    array (
      'action' => 1,
    ),
    4 => 
    array (
      'module' => 'default',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
