default:
  http_metas:
    content-type: text/html

  metas:
    title:        Joseph Borge Ltd.
    robots:       index, follow
    description:  Joseph Borge Ltd.
    keywords:     Joseph Borge Ltd.
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
