<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/09 12:07:53

$database = new sfPropelDatabase();
$database->initialize(array (
  'persistent' => true,
  'dsn' => 'mysql://svs:svs@localhost/ram_jbl',
), 'propel');
$this->databases['propel'] = $database;
