<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/09 12:07:53
sfConfig::add(array(
  'app_web_path' => 'http://ram.jbl.svs153/admin',
  'app_webpath' => 'http://ram.jbl.svs153',
  'app_upload_webpath' => 'http://ram.jbl.svs153/uploads/',
  'app_upload_file_path' => '/home/ramesh/web/www.jbl.com/web/uploads',
  'app_page' => 20,
));
