<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/09 12:08:01
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
