<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/02/09 12:08:07
$this->security = array (
  'changestatus' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
