<?php
// auto-generated by sfValidatorConfigHandler
// date: 2013/06/28 17:58:22

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
  'enable' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('title', 1, 'Title cannot be left blank', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
  'enable' => true,
), 'symfony/filter');
}
