<?php
// auto-generated by sfValidatorConfigHandler
// date: 2013/06/28 17:55:42

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
  'enable' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('contactus_data', 1, 'Please Enter Contact Us Data', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
  'enable' => true,
), 'symfony/filter');
}
